# Generated by Django 2.2 on 2019-04-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PleaseSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('CHAPELHILL', 'Chapel Hill'), ('DURHAMCITY', 'Durham'), ('CARRBORO', 'Carrboro'), ('HILLSBOROUGH', 'Hillsborough'), ('RALEIGH', 'Raleigh'), ('MEBANE', 'Mebane'), ('MORRISVILLE', 'Morrisville'), ('BINGHAM', 'Bingham'), ('CEDARGROVE', 'Cedar Grove'), ('ENO', 'Eno'), ('LITTLERIVER', 'Little River')], max_length=25)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('query_string_start', models.CharField(max_length=100)),
                ('query_string_end', models.CharField(max_length=100)),
                ('sf_field', models.CharField(max_length=100)),
            ],
        ),
    ]
