# Generated by Django 2.2 on 2019-04-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pleasesearch_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='pleasesearch',
            name='counties',
            field=models.CharField(choices=[('Durham', 'Durham'), ('Orange', 'Orange'), ('Wake', 'Wake'), ('Caswell', 'Caswell'), ('Alamance', 'Alamance'), ('Chatham', 'Chatham'), ('Person', 'Person')], default=False, max_length=25),
            preserve_default=False,
        ),
    ]
