# Generated by Django 2.2 on 2019-04-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190417_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pleasesearch',
            name='categories',
            field=models.CharField(choices=[('Any category', 'Any category'), ('Emergency', 'Emergency'), ('Food', 'Food'), ('Housing', 'Housing'), ('Goods', 'Goods'), ('Transportation', 'Transportation'), ('Health', 'Health'), ('Finances', 'Finances'), ('Care', 'Care'), ('Education', 'Education'), ('Employment', 'Employment'), ('Legal', 'Legal'), ('Communication', 'Communication'), ('One Stop', 'One Stop')], max_length=25),
        ),
        migrations.AlterField(
            model_name='pleasesearch',
            name='counties',
            field=models.CharField(choices=[('Any county', 'Any county'), ('Durham', 'Durham'), ('Orange', 'Orange'), ('Wake', 'Wake'), ('Caswell', 'Caswell'), ('Alamance', 'Alamance'), ('Chatham', 'Chatham'), ('Person', 'Person')], max_length=25),
        ),
    ]
