# Generated by Django 2.2 on 2019-04-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190418_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='luckysearch',
            name='limit_by_name',
            field=models.BooleanField(default='True'),
        ),
    ]
