# Generated by Django 2.2 on 2019-04-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_luckysearch_limit_by_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuckyDanSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lucky_string', models.CharField(max_length=100)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('limit_by_name', models.BooleanField(default='True')),
            ],
        ),
    ]
