# Generated by Django 2.2 on 2019-04-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_luckydansearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lucky_string', models.CharField(max_length=100)),
            ],
        ),
    ]
